###  Yser sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
"name":"Manish yadav",
"company":"Company name",
"address":"Some address Sydney",
"phone":"7106151901",
"email":"m@gmail.com",
"password":"manish26"

}

###  User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
"email":"m@gmail.com",
"password":"manish26"
}


###  Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AZ21haWwuY29tIiwiaWF0IjoxNjMwMzAyNzE2LCJleHAiOjE2MzAzMDM2MTZ9.ymR-qN9JBzxD2LGx_Dlw2UifcU_5twxGwDNaSGL3U7g

### token routers


### Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AZ21haWwuY29tIiwiaWF0IjoxNjMwMzA2MzA1LCJleHAiOjE2MzI4OTgzMDV9.erhTlSMrbgDMxBcYC0kwVSLW-wY5o3dtnKvgfxQyp_0

### password reset endpoint
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email":"m@gmail.com"
}