###  Yser sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
"name":"Manish yadav",
"company":"Company name",
"address":"Some address Sydney",
"phone":"7106151901",
"email":"m@gmail.com",
"password":"manish26"

}

###  User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
"email":"m@gmail.com",
"password":"manish26"
}


###  Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AZ21haWwuY29tIiwiaWF0IjoxNjMwNTY1NDE3LCJleHAiOjE2MzMxNTc0MTd9.PwG3sNrCaOSrZzJ2pyx3dMhQqSmnogcJwGWQBksU0wo

### token routers


### Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AZ21haWwuY29tIiwiaWF0IjoxNjMwNTY1NDE3LCJleHAiOjE2MzMxNTc0MTd9.PwG3sNrCaOSrZzJ2pyx3dMhQqSmnogcJwGWQBksU0wo

### password reset endpoint
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email":"m@gmail.com"
}

### password new password endpoint
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email":"m@gmail.com",
    "pin":"628799",
    "newPassword":"manish26"
}

###user logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AZ21haWwuY29tIiwiaWF0IjoxNjMwNTY1NDE3LCJleHAiOjE2MzMxNTc0MTd9.PwG3sNrCaOSrZzJ2pyx3dMhQqSmnogcJwGWQBksU0wo

### To create new ticket
POST http://localhost:3001/v1/ticket
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AZ21haWwuY29tIiwiaWF0IjoxNjMwNTY1NDE3LCJleHAiOjE2MzMxNTc0MTd9.PwG3sNrCaOSrZzJ2pyx3dMhQqSmnogcJwGWQBksU0wo

{
    "subject":"form issue",
    "sender":"Manish",
    "message":"Contact form not working. please fix it as soon as possible"
}

### Get all tickets of specific user
GET http://localhost:3001/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AZ21haWwuY29tIiwiaWF0IjoxNjMwNTY1NDE3LCJleHAiOjE2MzMxNTc0MTd9.PwG3sNrCaOSrZzJ2pyx3dMhQqSmnogcJwGWQBksU0wo

### Get a specific ticket
GET http://localhost:3001/v1/ticket/61306e99a22dcffc8f46117b
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AZ21haWwuY29tIiwiaWF0IjoxNjMwNTY1NDE3LCJleHAiOjE2MzMxNTc0MTd9.PwG3sNrCaOSrZzJ2pyx3dMhQqSmnogcJwGWQBksU0wo

