###  Yser sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
"name":"Manish yadav",
"company":"Company name",
"address":"Some address Sydney",
"phone":"7106151901",
"email":"m@gmail.com",
"password":"manish26"

}

###  User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
"email":"m@gmail.com",
"password":"manish26"
}


###  Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AZ21haWwuY29tIiwiaWF0IjoxNjMwNTYxNDQwLCJleHAiOjE2MzA1NjIzNDB9.w5xswTL5Jmwej4NBEXsnnCMYxkrSIDun9nnOogUcJC4

### token routers


### Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AZ21haWwuY29tIiwiaWF0IjoxNjMwMzA2MzA1LCJleHAiOjE2MzI4OTgzMDV9.erhTlSMrbgDMxBcYC0kwVSLW-wY5o3dtnKvgfxQyp_0

### password reset endpoint
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email":"m@gmail.com"
}

### password new password endpoint
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email":"m@gmail.com",
    "pin":"628799",
    "newPassword":"manish26"
}

###user logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AZ21haWwuY29tIiwiaWF0IjoxNjMwNDc2NDI1LCJleHAiOjE2MzA0NzczMjV9.65Jt5OIAp3_Fcfe_hQFbJc_eplQ3NbvTjZduV5rHq4w

### To create new ticket
POST http://localhost:3001/v1/ticket
Content-Type: application/json

{
    "subject":"form issue",
    "sender":"Manish",
    "message":"Contact form not working. please fix it as soon as possible"
}
